# Generated by Django 4.2 on 2023-05-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingdetail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantDetail',
        ),
    ]
