# Generated by Django 4.2 on 2023-05-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rigister', '0002_user_delete_signup'),
        ('bookingdetail', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rigister.user'),
        ),
    ]
