# Generated by Django 4.2 on 2023-05-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
