# Generated by Django 4.2 on 2023-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(null=True, upload_to='formsdashboard/'),
        ),
    ]
