# Generated by Django 4.2 on 2023-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsdashboard', '0002_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(null=True, upload_to='C:/Project/thewebsite_travel/website_travel/home/static/img/'),
        ),
    ]
