# Generated by Django 4.2 on 2023-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsdashboard', '0003_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(null=True, upload_to='home/static/img/'),
        ),
    ]
