# Generated by Django 4.2 on 2023-05-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsdashboard', '0007_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(default=None, upload_to='img/slide/'),
        ),
    ]
