# Generated by Django 4.2 on 2023-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsdashboard', '0015_restaurantdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurantdetail',
            name='phone',
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='detail1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='detail2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='detail3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='detail4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='detail5',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
