# Generated by Django 4.2 on 2023-05-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsdashboard', '0018_alter_restaurantdetail_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='Default description', max_length=400),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detail1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detail2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detail3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detail4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='detail5',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='RestaurantDetail',
        ),
    ]
